add some dependency to build system

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -792,6 +792,10 @@ LTLIBOBJS
 LIBOBJS
 libcurl_LIBS
 libcurl_CFLAGS
+libswresample_LIBS
+libswresample_CFLAGS
+libavcodec_LIBS
+libavcodec_CFLAGS
 libavutil_LIBS
 libavutil_CFLAGS
 libavformat_LIBS
@@ -982,6 +986,10 @@ libavformat_CFLAGS
 libavformat_LIBS
 libavutil_CFLAGS
 libavutil_LIBS
+libavcodec_CFLAGS
+libavcodec_LIBS
+libswresample_CFLAGS
+libswresample_LIBS
 libcurl_CFLAGS
 libcurl_LIBS'
 
@@ -1684,6 +1692,14 @@ Some influential environment variables:
               C compiler flags for libavutil, overriding pkg-config
   libavutil_LIBS
               linker flags for libavutil, overriding pkg-config
+  libavcodec_CFLAGS
+              C compiler flags for libavcodec, overriding pkg-config
+  libavcodec_LIBS
+              linker flags for libavcodec, overriding pkg-config
+  libswresample_CFLAGS
+              C compiler flags for libswresample, overriding pkg-config
+  libswresample_LIBS
+              linker flags for libswresample, overriding pkg-config
   libcurl_CFLAGS
               C compiler flags for libcurl, overriding pkg-config
   libcurl_LIBS
@@ -4605,13 +4621,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:4608: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:4624: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4611: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:4627: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4614: output\"" >&5)
+  (eval echo "\"\$as_me:4630: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -5817,7 +5833,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5820 "configure"' > conftest.$ac_ext
+  echo '#line 5836 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7674,11 +7690,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7677: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7693: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7681: \$? = $ac_status" >&5
+   echo "$as_me:7697: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8013,11 +8029,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8016: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8032: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8020: \$? = $ac_status" >&5
+   echo "$as_me:8036: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8118,11 +8134,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8121: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8137: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8125: \$? = $ac_status" >&5
+   echo "$as_me:8141: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8173,11 +8189,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8176: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8192: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8180: \$? = $ac_status" >&5
+   echo "$as_me:8196: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10976,7 +10992,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10979 "configure"
+#line 10995 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11072,7 +11088,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11075 "configure"
+#line 11091 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14471,11 +14487,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14474: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14490: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14478: \$? = $ac_status" >&5
+   echo "$as_me:14494: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14570,11 +14586,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14573: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14589: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14577: \$? = $ac_status" >&5
+   echo "$as_me:14593: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14622,11 +14638,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14625: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14641: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14629: \$? = $ac_status" >&5
+   echo "$as_me:14645: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17613,12 +17629,12 @@ if test -n "$libavutil_CFLAGS"; then
     pkg_cv_libavutil_CFLAGS="$libavutil_CFLAGS"
  elif test -n "$PKG_CONFIG"; then
     if test -n "$PKG_CONFIG" && \
-    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libavutil >= 54.31.0\"") >&5
-  ($PKG_CONFIG --exists --print-errors "libavutil >= 54.31.0") 2>&5
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libavutil >= 54.31.100\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libavutil >= 54.31.100") 2>&5
   ac_status=$?
   $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_libavutil_CFLAGS=`$PKG_CONFIG --cflags "libavutil >= 54.31.0" 2>/dev/null`
+  pkg_cv_libavutil_CFLAGS=`$PKG_CONFIG --cflags "libavutil >= 54.31.100" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -17629,12 +17645,12 @@ if test -n "$libavutil_LIBS"; then
     pkg_cv_libavutil_LIBS="$libavutil_LIBS"
  elif test -n "$PKG_CONFIG"; then
     if test -n "$PKG_CONFIG" && \
-    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libavutil >= 54.31.0\"") >&5
-  ($PKG_CONFIG --exists --print-errors "libavutil >= 54.31.0") 2>&5
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libavutil >= 54.31.100\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libavutil >= 54.31.100") 2>&5
   ac_status=$?
   $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_libavutil_LIBS=`$PKG_CONFIG --libs "libavutil >= 54.31.0" 2>/dev/null`
+  pkg_cv_libavutil_LIBS=`$PKG_CONFIG --libs "libavutil >= 54.31.100" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -17652,14 +17668,14 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-	        libavutil_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "libavutil >= 54.31.0" 2>&1`
+	        libavutil_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "libavutil >= 54.31.100" 2>&1`
         else
-	        libavutil_PKG_ERRORS=`$PKG_CONFIG --print-errors "libavutil >= 54.31.0" 2>&1`
+	        libavutil_PKG_ERRORS=`$PKG_CONFIG --print-errors "libavutil >= 54.31.100" 2>&1`
         fi
 	# Put the nasty error message in config.log where it belongs
 	echo "$libavutil_PKG_ERRORS" >&5
 
-	{ { $as_echo "$as_me:$LINENO: error: Package requirements (libavutil >= 54.31.0) were not met:
+	{ { $as_echo "$as_me:$LINENO: error: Package requirements (libavutil >= 54.31.100) were not met:
 
 $libavutil_PKG_ERRORS
 
@@ -17670,7 +17686,7 @@ Alternatively, you may set the environment variables libavutil_CFLAGS
 and libavutil_LIBS to avoid the need to call pkg-config.
 See the pkg-config man page for more details.
 " >&5
-$as_echo "$as_me: error: Package requirements (libavutil >= 54.31.0) were not met:
+$as_echo "$as_me: error: Package requirements (libavutil >= 54.31.100) were not met:
 
 $libavutil_PKG_ERRORS
 
@@ -17721,6 +17737,224 @@ fi
 
 # Checks for ffmpeg_sender
 if test "x$ffmpeg_sender" = xyes; then
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for libavcodec" >&5
+$as_echo_n "checking for libavcodec... " >&6; }
+
+if test -n "$libavcodec_CFLAGS"; then
+    pkg_cv_libavcodec_CFLAGS="$libavcodec_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libavcodec >= 56.60.100\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libavcodec >= 56.60.100") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_libavcodec_CFLAGS=`$PKG_CONFIG --cflags "libavcodec >= 56.60.100" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$libavcodec_LIBS"; then
+    pkg_cv_libavcodec_LIBS="$libavcodec_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libavcodec >= 56.60.100\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libavcodec >= 56.60.100") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_libavcodec_LIBS=`$PKG_CONFIG --libs "libavcodec >= 56.60.100" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        libavcodec_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "libavcodec >= 56.60.100" 2>&1`
+        else
+	        libavcodec_PKG_ERRORS=`$PKG_CONFIG --print-errors "libavcodec >= 56.60.100" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$libavcodec_PKG_ERRORS" >&5
+
+	{ { $as_echo "$as_me:$LINENO: error: Package requirements (libavcodec >= 56.60.100) were not met:
+
+$libavcodec_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables libavcodec_CFLAGS
+and libavcodec_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+$as_echo "$as_me: error: Package requirements (libavcodec >= 56.60.100) were not met:
+
+$libavcodec_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables libavcodec_CFLAGS
+and libavcodec_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { $as_echo "$as_me:$LINENO: error: in \`$ac_pwd':" >&5
+$as_echo "$as_me: error: in \`$ac_pwd':" >&2;}
+{ { $as_echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables libavcodec_CFLAGS
+and libavcodec_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&5
+$as_echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables libavcodec_CFLAGS
+and libavcodec_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }; }
+else
+	libavcodec_CFLAGS=$pkg_cv_libavcodec_CFLAGS
+	libavcodec_LIBS=$pkg_cv_libavcodec_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	:
+fi
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for libswresample" >&5
+$as_echo_n "checking for libswresample... " >&6; }
+
+if test -n "$libswresample_CFLAGS"; then
+    pkg_cv_libswresample_CFLAGS="$libswresample_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libswresample >= 1.2.101\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libswresample >= 1.2.101") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_libswresample_CFLAGS=`$PKG_CONFIG --cflags "libswresample >= 1.2.101" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$libswresample_LIBS"; then
+    pkg_cv_libswresample_LIBS="$libswresample_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libswresample >= 1.2.101\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libswresample >= 1.2.101") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_libswresample_LIBS=`$PKG_CONFIG --libs "libswresample >= 1.2.101" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        libswresample_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "libswresample >= 1.2.101" 2>&1`
+        else
+	        libswresample_PKG_ERRORS=`$PKG_CONFIG --print-errors "libswresample >= 1.2.101" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$libswresample_PKG_ERRORS" >&5
+
+	{ { $as_echo "$as_me:$LINENO: error: Package requirements (libswresample >= 1.2.101) were not met:
+
+$libswresample_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables libswresample_CFLAGS
+and libswresample_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+$as_echo "$as_me: error: Package requirements (libswresample >= 1.2.101) were not met:
+
+$libswresample_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables libswresample_CFLAGS
+and libswresample_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { $as_echo "$as_me:$LINENO: error: in \`$ac_pwd':" >&5
+$as_echo "$as_me: error: in \`$ac_pwd':" >&2;}
+{ { $as_echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables libswresample_CFLAGS
+and libswresample_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&5
+$as_echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables libswresample_CFLAGS
+and libswresample_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }; }
+else
+	libswresample_CFLAGS=$pkg_cv_libswresample_CFLAGS
+	libswresample_LIBS=$pkg_cv_libswresample_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	:
+fi
 
 pkg_failed=no
 { $as_echo "$as_me:$LINENO: checking for libcurl" >&5
@@ -17831,6 +18065,10 @@ $as_echo "yes" >&6; }
 	:
 fi
 fi
+
+
+
+
 
 
 
