add ffmpeg_demuxer_source to autotools configuration

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -790,6 +790,10 @@ ac_subst_vars='am__EXEEXT_FALSE
 am__EXEEXT_TRUE
 LTLIBOBJS
 LIBOBJS
+libavutil_LIBS
+libavutil_CFLAGS
+libavformat_LIBS
+libavformat_CFLAGS
 glib_LIBS
 glib_CFLAGS
 libnetembryo_LIBS
@@ -810,6 +814,8 @@ CXXFLAGS
 CXX
 INCLUDE_RTSP_PORT_FALSE
 INCLUDE_RTSP_PORT_TRUE
+INCLUDE_FFMPEG_DEMUXER_SOURCE_FALSE
+INCLUDE_FFMPEG_DEMUXER_SOURCE_TRUE
 INCLUDE_PROXY_SOURCE_FALSE
 INCLUDE_PROXY_SOURCE_TRUE
 INCLUDE_RTMP_SOURCE_FALSE
@@ -940,6 +946,7 @@ enable_libtool_lock
 with_rtsp_source
 with_rtmp_source
 with_proxy_source
+with_ffmpeg_demuxer_source
 with_rtsp_port
 '
       ac_precious_vars='build_alias
@@ -965,7 +972,11 @@ librtmp_LIBS
 libnetembryo_CFLAGS
 libnetembryo_LIBS
 glib_CFLAGS
-glib_LIBS'
+glib_LIBS
+libavformat_CFLAGS
+libavformat_LIBS
+libavutil_CFLAGS
+libavutil_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1620,6 +1631,9 @@ Optional Packages:
                           [default=no]
   --with-proxy-source     would contains the stsw_proxy_source program
                           [default=yes]
+  --with-ffmpeg-demuxer-source
+                          would contains the ffmpeg-demuxer-source program
+                          [default=yes]
   --with-rtsp-port        would contains the stsw_rtsp_port program
                           [default=yes]
 
@@ -1653,6 +1667,14 @@ Some influential environment variables:
               linker flags for libnetembryo, overriding pkg-config
   glib_CFLAGS C compiler flags for glib, overriding pkg-config
   glib_LIBS   linker flags for glib, overriding pkg-config
+  libavformat_CFLAGS
+              C compiler flags for libavformat, overriding pkg-config
+  libavformat_LIBS
+              linker flags for libavformat, overriding pkg-config
+  libavutil_CFLAGS
+              C compiler flags for libavutil, overriding pkg-config
+  libavutil_LIBS
+              linker flags for libavutil, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -4570,13 +4592,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:4573: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:4595: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4576: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:4598: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4579: output\"" >&5)
+  (eval echo "\"\$as_me:4601: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -5782,7 +5804,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5785 "configure"' > conftest.$ac_ext
+  echo '#line 5807 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7639,11 +7661,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7642: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7664: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7646: \$? = $ac_status" >&5
+   echo "$as_me:7668: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7978,11 +8000,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7981: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8003: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7985: \$? = $ac_status" >&5
+   echo "$as_me:8007: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8083,11 +8105,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8086: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8108: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8090: \$? = $ac_status" >&5
+   echo "$as_me:8112: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8138,11 +8160,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8141: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8163: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8145: \$? = $ac_status" >&5
+   echo "$as_me:8167: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10941,7 +10963,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10944 "configure"
+#line 10966 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11037,7 +11059,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11040 "configure"
+#line 11062 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11325,6 +11347,26 @@ else
   INCLUDE_PROXY_SOURCE_TRUE='#'
   INCLUDE_PROXY_SOURCE_FALSE=
 fi
+
+
+
+# Check whether --with-ffmpeg-demuxer-source was given.
+if test "${with_ffmpeg_demuxer_source+set}" = set; then
+  withval=$with_ffmpeg_demuxer_source; ffmpeg_demuxer_source=${withval}
+else
+  ffmpeg_demuxer_source=yes
+fi
+
+
+
+ if test "x$ffmpeg_demuxer_source" = xyes; then
+  INCLUDE_FFMPEG_DEMUXER_SOURCE_TRUE=
+  INCLUDE_FFMPEG_DEMUXER_SOURCE_FALSE='#'
+else
+  INCLUDE_FFMPEG_DEMUXER_SOURCE_TRUE='#'
+  INCLUDE_FFMPEG_DEMUXER_SOURCE_FALSE=
+fi
+
 
 
 
@@ -14398,11 +14440,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14401: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14443: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14405: \$? = $ac_status" >&5
+   echo "$as_me:14447: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14497,11 +14539,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14500: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14542: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14504: \$? = $ac_status" >&5
+   echo "$as_me:14546: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14549,11 +14591,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14552: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14594: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14556: \$? = $ac_status" >&5
+   echo "$as_me:14598: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17420,6 +17462,232 @@ fi
 
 
 
+# Checks for stsw_rtmp_source
+if test "x$ffmpeg_demuxer_source" = xyes; then
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for libavformat" >&5
+$as_echo_n "checking for libavformat... " >&6; }
+
+if test -n "$libavformat_CFLAGS"; then
+    pkg_cv_libavformat_CFLAGS="$libavformat_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libavformat >= 56.40.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libavformat >= 56.40.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_libavformat_CFLAGS=`$PKG_CONFIG --cflags "libavformat >= 56.40.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$libavformat_LIBS"; then
+    pkg_cv_libavformat_LIBS="$libavformat_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libavformat >= 56.40.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libavformat >= 56.40.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_libavformat_LIBS=`$PKG_CONFIG --libs "libavformat >= 56.40.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        libavformat_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "libavformat >= 56.40.0" 2>&1`
+        else
+	        libavformat_PKG_ERRORS=`$PKG_CONFIG --print-errors "libavformat >= 56.40.0" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$libavformat_PKG_ERRORS" >&5
+
+	{ { $as_echo "$as_me:$LINENO: error: Package requirements (libavformat >= 56.40.0) were not met:
+
+$libavformat_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables libavformat_CFLAGS
+and libavformat_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+$as_echo "$as_me: error: Package requirements (libavformat >= 56.40.0) were not met:
+
+$libavformat_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables libavformat_CFLAGS
+and libavformat_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { $as_echo "$as_me:$LINENO: error: in \`$ac_pwd':" >&5
+$as_echo "$as_me: error: in \`$ac_pwd':" >&2;}
+{ { $as_echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables libavformat_CFLAGS
+and libavformat_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&5
+$as_echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables libavformat_CFLAGS
+and libavformat_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }; }
+else
+	libavformat_CFLAGS=$pkg_cv_libavformat_CFLAGS
+	libavformat_LIBS=$pkg_cv_libavformat_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	:
+fi
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for libavutil" >&5
+$as_echo_n "checking for libavutil... " >&6; }
+
+if test -n "$libavutil_CFLAGS"; then
+    pkg_cv_libavutil_CFLAGS="$libavutil_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libavutil >= 56.31.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libavutil >= 56.31.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_libavutil_CFLAGS=`$PKG_CONFIG --cflags "libavutil >= 56.31.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$libavutil_LIBS"; then
+    pkg_cv_libavutil_LIBS="$libavutil_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libavutil >= 56.31.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libavutil >= 56.31.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_libavutil_LIBS=`$PKG_CONFIG --libs "libavutil >= 56.31.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        libavutil_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "libavutil >= 56.31.0" 2>&1`
+        else
+	        libavutil_PKG_ERRORS=`$PKG_CONFIG --print-errors "libavutil >= 56.31.0" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$libavutil_PKG_ERRORS" >&5
+
+	{ { $as_echo "$as_me:$LINENO: error: Package requirements (libavutil >= 56.31.0) were not met:
+
+$libavutil_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables libavutil_CFLAGS
+and libavutil_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+$as_echo "$as_me: error: Package requirements (libavutil >= 56.31.0) were not met:
+
+$libavutil_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables libavutil_CFLAGS
+and libavutil_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { $as_echo "$as_me:$LINENO: error: in \`$ac_pwd':" >&5
+$as_echo "$as_me: error: in \`$ac_pwd':" >&2;}
+{ { $as_echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables libavutil_CFLAGS
+and libavutil_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&5
+$as_echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables libavutil_CFLAGS
+and libavutil_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }; }
+else
+	libavutil_CFLAGS=$pkg_cv_libavutil_CFLAGS
+	libavutil_LIBS=$pkg_cv_libavutil_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	:
+fi
+fi
+
+
+
+
+
 
 # Checks for header files.
 
@@ -18777,6 +19045,13 @@ if test -z "${INCLUDE_PROXY_SOURCE_TRUE}" && test -z "${INCLUDE_PROXY_SOURCE_FAL
   { { $as_echo "$as_me:$LINENO: error: conditional \"INCLUDE_PROXY_SOURCE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 $as_echo "$as_me: error: conditional \"INCLUDE_PROXY_SOURCE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${INCLUDE_FFMPEG_DEMUXER_SOURCE_TRUE}" && test -z "${INCLUDE_FFMPEG_DEMUXER_SOURCE_FALSE}"; then
+  { { $as_echo "$as_me:$LINENO: error: conditional \"INCLUDE_FFMPEG_DEMUXER_SOURCE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+$as_echo "$as_me: error: conditional \"INCLUDE_FFMPEG_DEMUXER_SOURCE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -21127,6 +21402,7 @@ StreamSwitch program path ............ : $bindir
 stsw_rtsp_source included............. : $rtsp_source
 stsw_rtmp_source included ............ : $rtmp_source
 stsw_proxy_source included ........... : $proxy_source
+ffmpeg_demuxer_source included ....... : $ffmpeg_demuxer_source
 stsw_rtsp_port included .............. : $rtsp_port
 
 
@@ -21147,6 +21423,7 @@ StreamSwitch program path ............ : $bindir
 stsw_rtsp_source included............. : $rtsp_source
 stsw_rtmp_source included ............ : $rtmp_source
 stsw_proxy_source included ........... : $proxy_source
+ffmpeg_demuxer_source included ....... : $ffmpeg_demuxer_source
 stsw_rtsp_port included .............. : $rtsp_port
 
 
