add rtmp_source to autotools system
fix some problem

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -790,6 +790,8 @@ ac_subst_vars='am__EXEEXT_FALSE
 am__EXEEXT_TRUE
 LTLIBOBJS
 LIBOBJS
+librtmp_LIBS
+librtmp_CFLAGS
 protobuf_LIBS
 protobuf_CFLAGS
 zeromq_LIBS
@@ -802,6 +804,8 @@ CXXDEPMODE
 ac_ct_CXX
 CXXFLAGS
 CXX
+INCLUDE_RTMP_SOURCE_FALSE
+INCLUDE_RTMP_SOURCE_TRUE
 INCLUDE_RTSP_SOURCE_FALSE
 INCLUDE_RTSP_SOURCE_TRUE
 CPP
@@ -926,6 +930,7 @@ enable_dependency_tracking
 with_gnu_ld
 enable_libtool_lock
 with_rtsp_source
+with_rtmp_source
 '
       ac_precious_vars='build_alias
 host_alias
@@ -944,7 +949,9 @@ PKG_CONFIG
 zeromq_CFLAGS
 zeromq_LIBS
 protobuf_CFLAGS
-protobuf_LIBS'
+protobuf_LIBS
+librtmp_CFLAGS
+librtmp_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1595,6 +1602,8 @@ Optional Packages:
   --with-gnu-ld           assume the C compiler uses GNU ld [default=no]
   --with-rtsp-source      would contains the stsw_rtsp_source program
                           [default=yes]
+  --with-rtmp-source      would contains the stsw_rtmp_source program
+                          [default=yes]
 
 Some influential environment variables:
   CC          C compiler command
@@ -1616,6 +1625,10 @@ Some influential environment variables:
               C compiler flags for protobuf, overriding pkg-config
   protobuf_LIBS
               linker flags for protobuf, overriding pkg-config
+  librtmp_CFLAGS
+              C compiler flags for librtmp, overriding pkg-config
+  librtmp_LIBS
+              linker flags for librtmp, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -4533,13 +4546,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:4536: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:4549: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4539: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:4552: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4542: output\"" >&5)
+  (eval echo "\"\$as_me:4555: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -5745,7 +5758,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5748 "configure"' > conftest.$ac_ext
+  echo '#line 5761 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7602,11 +7615,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7605: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7618: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7609: \$? = $ac_status" >&5
+   echo "$as_me:7622: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7941,11 +7954,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7944: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7957: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7948: \$? = $ac_status" >&5
+   echo "$as_me:7961: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8046,11 +8059,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8049: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8062: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8053: \$? = $ac_status" >&5
+   echo "$as_me:8066: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8101,11 +8114,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8104: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8117: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8108: \$? = $ac_status" >&5
+   echo "$as_me:8121: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10904,7 +10917,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10907 "configure"
+#line 10920 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11000,7 +11013,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11003 "configure"
+#line 11016 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11247,6 +11260,25 @@ fi
 else
   INCLUDE_RTSP_SOURCE_TRUE='#'
   INCLUDE_RTSP_SOURCE_FALSE=
+fi
+
+
+
+
+# Check whether --with-rtmp-source was given.
+if test "${with_rtmp_source+set}" = set; then
+  withval=$with_rtmp_source; rtmp_source=${withval}
+else
+  rtmp_source=yes
+fi
+
+
+ if test "x$rtmp_source" = xyes; then
+  INCLUDE_RTMP_SOURCE_TRUE=
+  INCLUDE_RTMP_SOURCE_FALSE='#'
+else
+  INCLUDE_RTMP_SOURCE_TRUE='#'
+  INCLUDE_RTMP_SOURCE_FALSE=
 fi
 
 
@@ -14301,11 +14333,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14304: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14336: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14308: \$? = $ac_status" >&5
+   echo "$as_me:14340: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14400,11 +14432,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14403: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14435: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14407: \$? = $ac_status" >&5
+   echo "$as_me:14439: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14452,11 +14484,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14455: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14487: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14459: \$? = $ac_status" >&5
+   echo "$as_me:14491: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16820,6 +16852,121 @@ fi
 
 
 
+if test "x$rtmp_source" = xyes; then
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for librtmp" >&5
+$as_echo_n "checking for librtmp... " >&6; }
+
+if test -n "$librtmp_CFLAGS"; then
+    pkg_cv_librtmp_CFLAGS="$librtmp_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"librtmp >= v2.3\"") >&5
+  ($PKG_CONFIG --exists --print-errors "librtmp >= v2.3") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_librtmp_CFLAGS=`$PKG_CONFIG --cflags "librtmp >= v2.3" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$librtmp_LIBS"; then
+    pkg_cv_librtmp_LIBS="$librtmp_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"librtmp >= v2.3\"") >&5
+  ($PKG_CONFIG --exists --print-errors "librtmp >= v2.3") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_librtmp_LIBS=`$PKG_CONFIG --libs "librtmp >= v2.3" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        librtmp_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "librtmp >= v2.3" 2>&1`
+        else
+	        librtmp_PKG_ERRORS=`$PKG_CONFIG --print-errors "librtmp >= v2.3" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$librtmp_PKG_ERRORS" >&5
+
+	{ { $as_echo "$as_me:$LINENO: error: Package requirements (librtmp >= v2.3) were not met:
+
+$librtmp_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables librtmp_CFLAGS
+and librtmp_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+$as_echo "$as_me: error: Package requirements (librtmp >= v2.3) were not met:
+
+$librtmp_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables librtmp_CFLAGS
+and librtmp_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { $as_echo "$as_me:$LINENO: error: in \`$ac_pwd':" >&5
+$as_echo "$as_me: error: in \`$ac_pwd':" >&2;}
+{ { $as_echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables librtmp_CFLAGS
+and librtmp_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&5
+$as_echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables librtmp_CFLAGS
+and librtmp_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }; }
+else
+	librtmp_CFLAGS=$pkg_cv_librtmp_CFLAGS
+	librtmp_LIBS=$pkg_cv_librtmp_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	:
+fi
+fi
+
+
+
+
 # Checks for header files.
 
 
@@ -16829,7 +16976,8 @@ fi
 
 
 
-for ac_header in fcntl.h stdint.h stdlib.h string.h sys/time.h unistd.h czmq.h zmq.h
+
+for ac_header in fcntl.h stdint.h stdlib.h string.h sys/time.h unistd.h czmq.h zmq.h librtmp/rtmp.h
 do
 as_ac_Header=`$as_echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
@@ -17984,7 +18132,7 @@ done
 
 
 # generate Makefiles
-ac_config_files="$ac_config_files Makefile libstreamswitch/Makefile libstreamswitch/samples/Makefile libstreamswitch/libstreamswitch.pc sources/stsw_rtsp_source/Makefile"
+ac_config_files="$ac_config_files Makefile libstreamswitch/Makefile libstreamswitch/samples/Makefile libstreamswitch/libstreamswitch.pc sources/stsw_rtsp_source/Makefile sources/stsw_rtmp_source/Makefile"
 
 
 # Generate other makefiles
@@ -18162,6 +18310,13 @@ if test -z "${INCLUDE_RTSP_SOURCE_TRUE}" && test -z "${INCLUDE_RTSP_SOURCE_FALSE
   { { $as_echo "$as_me:$LINENO: error: conditional \"INCLUDE_RTSP_SOURCE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 $as_echo "$as_me: error: conditional \"INCLUDE_RTSP_SOURCE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${INCLUDE_RTMP_SOURCE_TRUE}" && test -z "${INCLUDE_RTMP_SOURCE_FALSE}"; then
+  { { $as_echo "$as_me:$LINENO: error: conditional \"INCLUDE_RTMP_SOURCE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+$as_echo "$as_me: error: conditional \"INCLUDE_RTMP_SOURCE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -19031,6 +19186,7 @@ do
     "libstreamswitch/samples/Makefile") CONFIG_FILES="$CONFIG_FILES libstreamswitch/samples/Makefile" ;;
     "libstreamswitch/libstreamswitch.pc") CONFIG_FILES="$CONFIG_FILES libstreamswitch/libstreamswitch.pc" ;;
     "sources/stsw_rtsp_source/Makefile") CONFIG_FILES="$CONFIG_FILES sources/stsw_rtsp_source/Makefile" ;;
+    "sources/stsw_rtmp_source/Makefile") CONFIG_FILES="$CONFIG_FILES sources/stsw_rtmp_source/Makefile" ;;
 
   *) { { $as_echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 $as_echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
